### ISSUE TITLE
Versions of FFMPEG and OpenCV

### ISSUE THREAD

**Issue by ckemere** [bothlab/pomidaq#1] opened 2019-09-01 22:02 UTC
I believe that I've successfully lowered the version requirements for FFMPEG and OpenCV for compiling to ones that I can pull in with apt-get in Ubuntu 18.04. Should I submit a pull request about this?

find_package(OpenCV 3.2 REQUIRED)
find_package(FFmpeg 57.00 REQUIRED COMPONENTS avcodec avutil avformat swscale)

**Comment by ckemere** [comment] 2019-09-02 04:22
Update - we're also using the driver timestamps for frame synchronization, and I just discovered that there's a bug in how the timestamps are recorded in OpenCV 3.2. So in my version, I'm now actually requiring 3.4 (which effectively means 4.1 b/c it requires building from source).

**Comment by ximion** [comment] 2019-09-05 13:27
Hi!
> I believe that I've successfully lowered the version requirements for FFMPEG and OpenCV for compiling to ones that I can pull in with apt-get in Ubuntu 18.04. Should I submit a pull request about this?

The version requirements are quite deliberate. I had quite a bit of trouble in figuring out why certain settings were not working as intended, and it turned out that differences in the OpenCV API and (V4L) backend were to blame. The things sent over the wire are different with different versions of OpenCV (tested by intercepting the USB communication). The 4.x series of OpenCV works pretty well and that's what the software was finally adjusted for, as that's the most future-proof version (as OpenCV 4.x will highly likely be default in Ubuntu 20.04).
So tl;dr on OpenCV if you lower the version you really need to be sure that everything works as intended. The easiest check is often to just change the excitation LEDs power and see if it can be adjusted smoothly from lowest to highest intensity. This *may* work with older OpenCV, but I can't guarantee it (that's the reason for the high version requirement afterall). You could adjust the code to work with a different version though by adjusting the limits for each camera property, but I actually would like to keep this simple and not add settings for each different OpenCV version.
If you can confirm though that a certain OpenCV version works with the current code, I think adding an exception for that version may make sense.

Thinks are different for FFmpeg - that only has a high version requirement because I was playing around with the AV1 codec, which currently simply doesn't have the encoding speed necessary to record data with high FPS in real time unless you have dedicated hardware. The version requirement is simply whatever was available in Debian 10 (where the software is developed on). Lowering it shouldn't actually have any drawback (if all the API is supported that PoMiDAQ uses).

> Update - we're also using the driver timestamps for frame synchronization, and I just discovered that there's a bug in how the timestamps are recorded in OpenCV 3.2. So in my version, I'm now actually requiring 3.4 (which effectively means 4.1 b/c it requires building from source).

Hehe ^^ - Older OpenCV versions do have some serious bugs in key functionality in image acquisition. I actually also had some code lying around to take timestamps from the driver, which I didn't use because driver timestamps weren't reliable. This seems to work well now though, so I committed the changes to master now, maybe you'll find that useful as well (the main purpose of the changes was actually to integrate the Miniscope library with a different project).

**Comment by ckemere** [comment] 2019-09-05 21:07
Awesome. I'm definitely surprised that the differences are that big, but I realize that V4L CAP setting is less widely implemented. (Before I found this project, I was exploring using libavdevice or QT for capture to avoid the OpenCV dependency, but neither implement changing camera settings.)

**Comment by ckemere** [comment] 2019-09-05 23:05
With regard to frameTimestamps, I've chosen a different approach than your most recent commit. (Take a look at my fork if you're interested - http://github.com/ckemere/pomidaq .) The biggest difference is that I want the actual raw CLOCK_MONOTONIC times associated with the frames. This allows us to synchronize with behavioral video with minimal friction. 

You can see the patched version of guvcview we use here - https://github.com/ckemere/guvcview
Normally guvcview also 0-bases the timestamps for data that it writes to disk. But we've patched it to remove the 0 offset so that its frames (which also use V4L for acquisition b/c we use a webcam) are in the same timebase. Simple and sweet!

**Comment by ximion** [comment] 2019-09-17 12:02
> Awesome. I'm definitely surprised that the differences are that big, but I realize that V4L CAP setting is less widely implemented. (Before I found this project, I was exploring using libavdevice or QT for capture to avoid the OpenCV dependency, but neither implement changing camera settings.)

The differences are just as bad on Windows as they are on Linux though, so you apparently can't escape this. My initial attempt was to write this software accessing V4L directly, but since people also needed a Windows version that plan was scrapped again (because writing another abstraction layer simply didn't make sense).



> With regard to frameTimestamps, I've chosen a different approach than your most recent commit. (Take a look at my fork if you're interested - [http://github.com/ckemere/pomidaq](https://github.com/ckemere/pomidaq) .) The biggest difference is that I want the actual raw CLOCK_MONOTONIC times associated with the frames. This allows us to synchronize with behavioral video with minimal friction.

This does make sense when running two different tools alongside each other. The libminiscope library is used in another of our projects, [MazeAmaze](https://github.com/bothlab/mazeamaze), which uses C++ standard time types as well, so for that usecase having the realtime-steadyclock makes sense.

> You can see the patched version of guvcview we use here - https://github.com/ckemere/guvcview
> Normally guvcview also 0-bases the timestamps for data that it writes to disk. But we've patched it to remove the 0 offset so that its frames (which also use V4L for acquisition b/c we use a webcam) are in the same timebase. Simple and sweet!

What I could maybe do is add an option to PoMiDAQ or its library to save the initial CLOCK_MONOTONIC time to a file as well. With that and the zero-based indices, calculating the monotonic time for all frames should be simple.
I don't really want to change the counting mechanism or make it switchable between two modes, because that will certainly lead to major confusion later.

In any case though I am very glad that you find this software useful! :-)

**Comment by ximion** [comment] 2019-10-22 06:05
I'm closing this for now as answered question, we can split it into actionable issues later, if that is even necessray still. :-)

**Closed as completed by ximion** 2019-10-22 06:05 UTC
Labels: question

**Comment by ximion** [comment] 2020-02-03 17:06
@ckemere PoMiDAQ has an option to switch between UNIX timestamps and start-from-zero timestamps. This isn't tested well, but should work fine. Also, there's an option to set the upper framerate limit now, for people who have faster Miniscopes ;-)
